"""Mapping colonnes brutes NAV -> noms standardisés et métadonnées PSPP."""

RAW_TO_STANDARD = {
    # ---- Anciens noms (dataset original) ----
    "Auto No": "auto_no",
    "Location": "location",
    "Silo Btes": "silo_btes",
    "Numero": "numero",
    "Item no": "item_no",
    "No2": "no2",
    "Description FR": "description_fr",
    "Description EN": "description_en",
    "Document Type": "document_type",
    "bon de commande": "purchase_order",
    "Fournisseur": "supplier_code",
    "nom fourn": "supplier_name",
    "Recyclé Vierge": "recycled_virgin",
    "Recycl\u00e9 Vierge": "recycled_virgin",
    "Fluidité g 10min": "fluidity_g_10min",
    "Fluidit\u00e9 g 10min": "fluidity_g_10min",
    "Mi": "mi",
    "HLMI": "hlmi",
    "Densité g cm3": "density_g_cm3",
    "Densit\u00e9 g cm3": "density_g_cm3",
    "Densité g cm3 plaq": "density_plaque_g_cm3",
    "Densit\u00e9 g cm3 plaq": "density_plaque_g_cm3",
    "Noir de carbone": "carbon_black",
    "Cendres": "ash",
    "Onset": "onset",
    "Peak": "peak",
    "Delta H": "delta_h",
    "PP": "pp",
    "OIT min": "oit_min",
    "IZod": "izod",
    "flexion": "flexion",
    "Cell Class": "cell_class",
    "Quantité kg": "quantity_kg",
    "Quantit\u00e9 kg": "quantity_kg",
    "Date de réception": "reception_date",
    "Date de r\u00e9ception": "reception_date",
    "Date terminé": "completion_date",
    "Date termin\u00e9": "completion_date",
    "NCLS": "ncls",
    "PCT allongement": "pct_elongation",
    "Traction": "traction",
    "Temp C": "temp_c",
    "UCLS": "ucls",

    # ---- Nouveaux noms (dataset mai 2026) ----
    "AutoNo": "auto_no",
    "Emplacement": "location",
    "SiloBtes": "silo_btes",
    "No. Article": "item_no",
    "No. 2": "no2",
    "Type de document": "document_type",
    "Recherche Lot #": "lot_search",
    "# Bon de commande": "purchase_order",
    "Nom Fournisseur": "supplier_name",
    "Recycl\u00e9/Vierge": "recycled_virgin",
    "Fluidit\u00e9(g/10min)": "fluidity_g_10min",
    "flagDensit\u00e9": "flag_density",
    "Densit\u00e9 (g/cm3)": "density_g_cm3",
    "Densit\u00e9 (g/cm3) plaq": "density_plaque_g_cm3",
    "Noir de carbone(%)": "carbon_black",
    "Cendres(%)": "ash",
    "%PP": "pp",
    "OIT (min)": "oit_min",
    "Quantit\u00e9 (kg)": "quantity_kg",
    "Date de r\u00e9ception": "reception_date",
    "Date termin\u00e9": "completion_date",
    "PCT_allongement": "pct_elongation",
    "Temp (C)": "temp_c",
    "ESCR": "escr",
    "Note": "note",
    "Donn\u00e9e Compagnie": "company_data",

    # Variantes encodage
    "Recycl?/Vierge": "recycled_virgin",
    "Fluidit?(g/10min)": "fluidity_g_10min",
    "flagDensit?": "flag_density",
    "Densit? (g/cm3)": "density_g_cm3",
    "Densit? (g/cm3) plaq": "density_plaque_g_cm3",
    "Quantit? (kg)": "quantity_kg",
    "Donn?e Compagnie": "company_data",
}

FEATURE_METADATA = [
    {"raw": "Auto No", "standard": "auto_no", "family": "identifiant/traçabilité", "dtype": "int", "role": "id", "A": False, "B": False},
    {"raw": "Location", "standard": "location", "family": "contexte industriel", "dtype": "category", "role": "context", "A": False, "B": True},
    {"raw": "Silo Btes", "standard": "silo_btes", "family": "contexte industriel", "dtype": "category", "role": "context", "A": False, "B": False},
    {"raw": "Numero", "standard": "numero", "family": "identifiant/traçabilité", "dtype": "int", "role": "id", "A": False, "B": False},
    {"raw": "Item no", "standard": "item_no", "family": "identifiant/traçabilité", "dtype": "category", "role": "id", "A": False, "B": False},
    {"raw": "No2", "standard": "no2", "family": "identifiant/traçabilité", "dtype": "category", "role": "id", "A": False, "B": False},
    {"raw": "Description FR", "standard": "description_fr", "family": "texte libre", "dtype": "text", "role": "grade_proxy", "A": False, "B": True},
    {"raw": "Description EN", "standard": "description_en", "family": "texte libre", "dtype": "text", "role": "metadata", "A": False, "B": False},
    {"raw": "Document Type", "standard": "document_type", "family": "administratif", "dtype": "category", "role": "metadata", "A": False, "B": False},
    {"raw": "bon de commande", "standard": "purchase_order", "family": "identifiant/traçabilité", "dtype": "category", "role": "id", "A": False, "B": False},
    {"raw": "Fournisseur", "standard": "supplier_code", "family": "contexte industriel", "dtype": "category", "role": "supplier", "A": False, "B": True},
    {"raw": "nom fourn", "standard": "supplier_name", "family": "contexte industriel", "dtype": "category", "role": "supplier", "A": False, "B": True},
    {"raw": "Recyclé Vierge", "standard": "recycled_virgin", "family": "charges/composition", "dtype": "category", "role": "feature", "A": True, "B": True},
    {"raw": "Fluidité g 10min", "standard": "fluidity_g_10min", "family": "rhéologie/fluidité", "dtype": "float", "role": "feature", "A": True, "B": True},
    {"raw": "Mi", "standard": "mi", "family": "rhéologie/fluidité", "dtype": "float", "role": "feature", "A": True, "B": True},
    {"raw": "HLMI", "standard": "hlmi", "family": "rhéologie/fluidité", "dtype": "float", "role": "feature", "A": True, "B": True},
    {"raw": "Densité g cm3", "standard": "density_g_cm3", "family": "densité/structure", "dtype": "float", "role": "feature", "A": True, "B": True},
    {"raw": "Densité g cm3 plaq", "standard": "density_plaque_g_cm3", "family": "densité/structure", "dtype": "float", "role": "feature", "A": True, "B": True},
    {"raw": "Noir de carbone", "standard": "carbon_black", "family": "charges/composition", "dtype": "float", "role": "feature", "A": True, "B": True},
    {"raw": "Cendres", "standard": "ash", "family": "charges/composition", "dtype": "float", "role": "feature", "A": True, "B": True},
    {"raw": "Onset", "standard": "onset", "family": "analyse thermique", "dtype": "float", "role": "feature", "A": True, "B": True},
    {"raw": "Peak", "standard": "peak", "family": "analyse thermique", "dtype": "float", "role": "feature", "A": True, "B": True},
    {"raw": "Delta H", "standard": "delta_h", "family": "analyse thermique", "dtype": "float", "role": "feature", "A": True, "B": True},
    {"raw": "PP", "standard": "pp", "family": "charges/composition", "dtype": "float", "role": "feature", "A": True, "B": True},
    {"raw": "OIT min", "standard": "oit_min", "family": "propriétés oxydatives", "dtype": "float", "role": "target", "A": False, "B": False},
    {"raw": "IZod", "standard": "izod", "family": "propriétés mécaniques", "dtype": "float", "role": "target", "A": False, "B": False},
    {"raw": "flexion", "standard": "flexion", "family": "propriétés mécaniques", "dtype": "float", "role": "target", "A": False, "B": False},
    {"raw": "Cell Class", "standard": "cell_class", "family": "durabilité", "dtype": "float", "role": "target", "A": False, "B": False},
    {"raw": "Quantité kg", "standard": "quantity_kg", "family": "administratif", "dtype": "float", "role": "metadata", "A": False, "B": False},
    {"raw": "Date de réception", "standard": "reception_date", "family": "contexte industriel", "dtype": "datetime", "role": "date", "A": False, "B": "transformed"},
    {"raw": "Date terminé", "standard": "completion_date", "family": "administratif", "dtype": "datetime", "role": "metadata", "A": False, "B": False},
    {"raw": "NCLS", "standard": "ncls", "family": "propriétés mécaniques", "dtype": "float", "role": "target", "A": False, "B": False},
    {"raw": "PCT allongement", "standard": "pct_elongation", "family": "propriétés mécaniques", "dtype": "float", "role": "target", "A": False, "B": False},
    {"raw": "Traction", "standard": "traction", "family": "propriétés mécaniques", "dtype": "float", "role": "target", "A": False, "B": False},
    {"raw": "Temp C", "standard": "temp_c", "family": "durabilité", "dtype": "float", "role": "target", "A": False, "B": False},
    {"raw": "UCLS", "standard": "ucls", "family": "propriétés mécaniques", "dtype": "float", "role": "target", "A": False, "B": False},
    {"raw": "ESCR", "standard": "escr", "family": "durabilité", "dtype": "float", "role": "target", "A": False, "B": False},
    {"raw": "Note", "standard": "note", "family": "administratif", "dtype": "text", "role": "metadata", "A": False, "B": False},
    {"raw": "Donn\u00e9e Compagnie", "standard": "company_data", "family": "administratif", "dtype": "category", "role": "metadata", "A": False, "B": False},
    {"raw": "Recherche Lot #", "standard": "lot_search", "family": "identifiant/traçabilité", "dtype": "category", "role": "id", "A": False, "B": False},
    {"raw": "flagDensit\u00e9", "standard": "flag_density", "family": "qualité", "dtype": "category", "role": "metadata", "A": False, "B": False},
]
