"""Règles de validité des cibles NAV — à valider par expert Soleno."""
from __future__ import annotations

import pandas as pd

# Colonnes du tableau de règles
RULE_COLUMNS = [
    "target_name",
    "expected_unit",
    "min_physical_value",
    "max_physical_value",
    "negative_allowed",
    "zero_allowed",
    "outlier_method",
    "transformation_recommended",
    "classification_recommended",
    "ranking_recommended",
    "action_for_invalid_values",
    "action_for_extreme_values",
    "comment",
]

DEFAULT_TARGET_RULES: list[dict] = [
    {
        "target_name": "oit_min",
        "expected_unit": "min (OIT)",
        "min_physical_value": 0,
        "max_physical_value": 500,
        "negative_allowed": False,
        "zero_allowed": True,
        "outlier_method": "percentile_99",
        "transformation_recommended": "log1p",
        "classification_recommended": True,
        "ranking_recommended": True,
        "action_for_invalid_values": "flag_exclude_training",
        "action_for_extreme_values": "winsorize_p99",
        "comment": "Valeurs négatives et >500 min suspectes (erreur unité?). À valider Soleno.",
    },
    {
        "target_name": "ncls",
        "expected_unit": "h (NCLS)",
        "min_physical_value": 0,
        "max_physical_value": 200,
        "negative_allowed": False,
        "zero_allowed": False,
        "outlier_method": "iqr",
        "transformation_recommended": "none",
        "classification_recommended": True,
        "ranking_recommended": True,
        "action_for_invalid_values": "flag_exclude_training",
        "action_for_extreme_values": "winsorize_p95",
        "comment": "Durabilité — plage indicative, valider unités.",
    },
    {
        "target_name": "ucls",
        "expected_unit": "h (UCLS)",
        "min_physical_value": 0,
        "max_physical_value": 300,
        "negative_allowed": False,
        "zero_allowed": False,
        "outlier_method": "iqr",
        "transformation_recommended": "none",
        "classification_recommended": True,
        "ranking_recommended": True,
        "action_for_invalid_values": "flag_exclude_training",
        "action_for_extreme_values": "winsorize_p95",
        "comment": "Faible effectif — privilégier classification/ranking.",
    },
    {
        "target_name": "izod",
        "expected_unit": "J/m",
        "min_physical_value": 0,
        "max_physical_value": 2000,
        "negative_allowed": False,
        "zero_allowed": False,
        "outlier_method": "percentile_99",
        "transformation_recommended": "log1p",
        "classification_recommended": True,
        "ranking_recommended": True,
        "action_for_invalid_values": "flag_exclude_training",
        "action_for_extreme_values": "winsorize_p99",
        "comment": "Max observé >>2000 — erreurs de saisie probables.",
    },
    {
        "target_name": "traction",
        "expected_unit": "MPa",
        "min_physical_value": 0,
        "max_physical_value": 80,
        "negative_allowed": False,
        "zero_allowed": False,
        "outlier_method": "iqr",
        "transformation_recommended": "none",
        "classification_recommended": True,
        "ranking_recommended": True,
        "action_for_invalid_values": "flag_exclude_training",
        "action_for_extreme_values": "winsorize_p95",
        "comment": "Vérifier si unité MPa vs autre échelle.",
    },
    {
        "target_name": "pct_elongation",
        "expected_unit": "%",
        "min_physical_value": 0,
        "max_physical_value": 2000,
        "negative_allowed": False,
        "zero_allowed": False,
        "outlier_method": "percentile_99",
        "transformation_recommended": "log1p",
        "classification_recommended": True,
        "ranking_recommended": True,
        "action_for_invalid_values": "flag_exclude_training",
        "action_for_extreme_values": "winsorize_p99",
        "comment": "Allongement — valeurs >1000% à contrôler.",
    },
    {
        "target_name": "flexion",
        "expected_unit": "MPa",
        "min_physical_value": 0,
        "max_physical_value": 2000,
        "negative_allowed": False,
        "zero_allowed": False,
        "outlier_method": "iqr",
        "transformation_recommended": "none",
        "classification_recommended": True,
        "ranking_recommended": True,
        "action_for_invalid_values": "flag_exclude_training",
        "action_for_extreme_values": "winsorize_p95",
        "comment": "Module flexion — plage large dans NAV.",
    },
    {
        "target_name": "cell_class",
        "expected_unit": "code classe (PE)",
        "min_physical_value": None,
        "max_physical_value": None,
        "negative_allowed": False,
        "zero_allowed": True,
        "outlier_method": "categorical",
        "transformation_recommended": "categorical",
        "classification_recommended": True,
        "ranking_recommended": False,
        "action_for_invalid_values": "flag_only",
        "action_for_extreme_values": "flag_only",
        "comment": "Variable codée (ex. 324420) — classification uniquement, pas régression continue.",
    },
    {
        "target_name": "temp_c",
        "expected_unit": "°C",
        "min_physical_value": -50,
        "max_physical_value": 400,
        "negative_allowed": True,
        "zero_allowed": True,
        "outlier_method": "none",
        "transformation_recommended": "none",
        "classification_recommended": False,
        "ranking_recommended": False,
        "action_for_invalid_values": "reclassify_as_input",
        "action_for_extreme_values": "flag_only",
        "comment": "Variable procédé/descriptive — retirée des cibles de modélisation.",
    },
]


def rules_dataframe() -> pd.DataFrame:
    return pd.DataFrame(DEFAULT_TARGET_RULES, columns=RULE_COLUMNS)


def get_rule(target: str) -> dict:
    df = rules_dataframe()
    row = df[df["target_name"] == target]
    if row.empty:
        return {}
    return row.iloc[0].to_dict()
